# Generated by Django 2.2.6 on 2019-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=30)),
                ('startdate', models.CharField(default='', max_length=30)),
                ('rate', models.CharField(default='', max_length=30)),
                ('recruiter', models.CharField(default='', max_length=50)),
                ('posteddate', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
