# Generated by Django 2.2.6 on 2019-10-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobmarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created',
            new_name='createddate',
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobmarket.Job')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
