# Generated by Django 2.2.6 on 2019-10-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobmarket', '0002_auto_20191004_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='jobid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobspec', to='jobmarket.Job'),
        ),
    ]
