# Generated by Django 2.2.6 on 2019-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmarket', '0003_auto_20191004_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
