# Generated by Django 2.2.6 on 2019-10-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmarket', '0004_auto_20191004_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
