# Generated by Django 2.2.6 on 2019-10-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmarket', '0005_auto_20191004_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='createddate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='posteddate',
            new_name='posted_date',
        ),
    ]
