# Generated by Django 2.2.6 on 2019-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmarket', '0007_jobdescription_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='highlighted',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
