# Generated by Django 2.2.6 on 2019-10-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmarket', '0008_auto_20191004_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='highlighted',
        ),
    ]
